---
title: "Day 8 Activity- Data Viz"
author: "Kiran Favre"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(ggplot2)
```

## Task 1: Worst data viz

```{r}
space_launches <- read_csv(here("data", "space_launches.csv"))
```

```{r}
ggplot(data = space_launches, aes(y = agency, x = launch_year)) +
  geom_boxplot(aes(color = agency)) + theme_linedraw() +
  theme(panel.grid.major.x = element_line(color = "magenta"),
        axis.text.y = element_text(color = "orange", size = 10, family = "Comic Sans MS"),
        axis.text.x = element_text(color = "grey", size = 25),
        text = element_text(color = "purple"),
        panel.background = element_rect(color = "green", fill = "brown"))
        
  

  
```

## Task 2: Wrangling practice with SF GHG data

```{r}
sf_ghg <- read_csv(here("data", "San_Francisco_Communitywide_Greenhouse_Gas_Inventory.csv"))
```

```{r}
#make a summary table of total annual ghg emission by sector_general
ghg_total <- sf_ghg |> 
  group_by(Sector_General) |> 
  summarize(ghg_ann_total = sum(Emissions_mtCO2e))
```

```{r}
# create a summary tablw of total annual ghg emissions by year and commodity type
ghg_year <- sf_ghg |> 
  group_by(Calendar_Year,Commodity_Type) |> 
  summarize(ghg_ann_total = sum(Emissions_mtCO2e))
```

```{r}
#create a subset of the data that only contains observations from 2005 onward, only for obs where Sector_detail2 contains "PG&E" then limit to columns Calendar_year, Sector_Detail2 and Emissions_mtCO2e.


```
